# Generated by Django 5.0.3 on 2024-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الإسم المحلى')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الإسم الأجنبى')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الإسم المحلى')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الإسم الأجنبى')),
                ('is_stop', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الإسم المحلى')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الإسم الأجنبى')),
                ('codeUnit', models.CharField(max_length=50, verbose_name='رمز الوحده')),
            ],
        ),
    ]
