# Generated by Django 5.0.3 on 2024-05-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserR',
        ),
    ]
