# Generated by Django 5.0.3 on 2024-05-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name_fk',
            field=models.CharField(default=' ', max_length=50, verbose_name='اسم الصنف الأجنبى'),
        ),
        migrations.AddField(
            model_name='items',
            name='name_lo',
            field=models.CharField(default=' ', max_length=50, unique=True, verbose_name='اسم الصنف المحلى'),
        ),
    ]
