# Generated by Django 5.0.3 on 2024-06-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الإسم المحلى')),
                ('name_fk', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الجوال')),
                ('phone', models.CharField(max_length=50, verbose_name='الإسم الأجنبى')),
                ('is_stop', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
